// AUTH
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const PASSWORD_RESET_FAIL = 'PASSWORD_RESET_FAIL';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_CONFIRM_FAIL = 'PASSWORD_RESET_CONFIRM_FAIL';
export const PASSWORD_RESET_CONFIRM_SUCCESS = 'PASSWORD_RESET_CONFIRM_SUCCESS';


export const LOGOUT = 'LOGOUT';

// personal profile
export const CREATE_PERSONAL_PROFILE_SUCCESS = 'CREATE_PERSONAL_PROFILE_SUCCESS';
export const CREATE_PERSONAL_PROFILE_FAIL = 'CREATE_PERSONAL_PROFILE_FAIL';
export const FETCH_PERSONAL_PROFILE_SUCCESS = 'FETCH_PERSONAL_PROFILE_SUCCESS';
export const FETCH_PERSONAL_PROFILE_FAIL = 'FETCH_PERSONAL_PROFILE_FAIL';
export const GET_SINGLE_PERSONAL_PROFILE_SUCCESS = 'GET_PERSONAL_PROFILE_SUCCESS';
export const GET_SINGLE_PERSONAL_PROFILE_FAIL = 'GET_PERSONAL_PROFILE_FAIL';
export const UPDATE_PERSONAL_PROFILE_SUCCESS = 'UPDATE_PERSONAL_PROFILE_SUCCESS';
export const UPDATE_PERSONAL_PROFILE_FAIL = 'UPDATE_PERSONAL_PROFILE_FAIL';


// SETTINGS
export const TOGGLE_COLLAPSED_NAV = 'TOGGLE_COLLAPSE_MENU';
export const DRAWER_TYPE = 'DRAWER_TYPE';
export const FIXED_DRAWER = 'FIXED_DRAWER';
export const COLLAPSED_DRAWER = 'COLLAPSIBLE';
export const WINDOW_WIDTH = 'WINDOW-WIDTH';

// MESSAGE
export const SHOW_SUCCESS_MESSAGE = 'SHOW_SUCCESS_MESSAGE';
export const SHOW_ERROR_MESSAGE = 'SHOW_ERROR_MESSAGE';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';


// DASHBOARD
export const SHOW_SIDEBAR = 'SHOW_SIDEBAR'
export const FETCH_START = 'FETCH_START';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_ERROR = 'FETCH_ERROR';


// category
export const FUND_RAISE_BUTTON_CLICKED = 'FUND_RAISE_BUTTON_CLICKED'
export const FUND_RAISE_CATEGORIES = 'FUND_RAISE_CATEGORIES'

export const VERIFY_PAYSTACK = 'VERIIFY_PAYSTACK'

// TOGGLE DASHBOARD SIDENAV
export const TOGGLE_DASHBOARD_SIDENAV = 'TOGGLE_DASHBOARD_SIDENAV'
export const TOGGLE_DASHBOARD_MOBILE_SIDENAV = 'TOGGLE_DASHBOARD_MOBILE_SIDENAV'


// CONTRIBUTION

export const FETCH_CONTRIBUTION_TARGET_SUCCESS = "FETCH_CONTRIBUTION_TARGET_SUCCESS";
export const FETCH_CONTRIBUTION_TARGET_FAIL = "FETCH_CONTRIBUTION_TARGET_FAIL";
export const FETCH_CONTRIBUTION_DAILY_SUCCESS = "FETCH_CONTRIBUTION_DAILY_SUCCESS";
export const FETCH_CONTRIBUTION_DAILY_FAIL = "FETCH_CONTRIBUTION_DAILY_FAIL";
export const FETCH_BANK_MAIN_SUCCESS = "FETCH_BANK_MAIN_SUCCESS";
export const FETCH_BANK_MAIN_FAIL = "FETCH_BANK_MAIN_FAIL";
export const FETCH_BANK_BONUS_SUCCESS = "FETCH_BANK_BONUS_SUCCESS";
export const FETCH_BANK_BONUS_FAIL = "FETCH_BANK_BONUS_FAIL";


// PROJECTS
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const FETCH_ALL_PROJECT_SUCCESS = "FETCH_ALL_PROJECT_SUCCESS";
export const FETCH_SINGLE_PROJECT_SUCCESS = "FETCH_SINGLE_PROJECT_SUCCESS";
export const FETCH_PROJECT_SUCCESS = "FETCH_PROJECT_SUCCESS";
export const FETCH_ALL_PROJECT_FAIL = "FETCH_ALL_PROJECT_FAIL";
export const FETCH_SINGLE_PROJECT_FAIL = "FETCH_SINGLE_PROJECT_FAIL";
export const CREATE_PROJECT_FAIL = "CREATE_PROJECT_FAIL";
export const FETCH_PROJECT_FAIL = "FETCH_PROJECT_FAIL";

export const CREATE_DONATION_CASH_SUCCESS = 'CREATE_DONATION_CASH_SUCCESS';
export const CREATE_DONATION_CASH_FAIL= ' CREATE_DONATION_CASH_FAIL';
export const UPDATE_DONATION_CASH_SUCCESS = 'UPDATE_DONATION_CASH_SUCCESS';
export const UPDATE_DONATION_CASH_FAIL= ' UPDATE_DONATION_CASH_FAIL';
export const DELETE_DONATION_CASH_SUCCESS = 'DELETE_DONATION_CASH_SUCCESS';
export const DELETE_DONATION_CASH_FAIL= ' DELETE_DONATION_CASH_FAIL';
export const FETCH_DONATION_CASH_SUCCESS= ' FETCH_DONATION_CASH_SUCCESS';
export const FETCH_DONATION_CASH_FAIL= ' FETCH_DONATION_CASH_FAIL';


export const CREATE_DONATION_ITEM_SUCCESS = 'CREATE_DONATION_ITEM_SUCCESS';
export const CREATE_DONATION_ITEM_FAIL= ' CREATE_DONATION_ITEM_FAIL';
export const UPDATE_DONATION_ITEM_SUCCESS = 'UPDATE_DONATION_ITEM_SUCCESS';
export const UPDATE_DONATION_ITEM_FAIL= ' UPDATE_DONATION_ITEM_FAIL';
export const DELETE_DONATION_ITEM_SUCCESS = 'DELETE_DONATION_ITEM_SUCCESS';
export const DELETE_DONATION_ITEM_FAIL= ' DELETE_DONATION_ITEM_FAIL';
export const FETCH_DONATION_ITEM_SUCCESS= ' FETCH_DONATION_ITEM_SUCCESS';
export const FETCH_DONATION_ITEM_FAIL= ' FETCH_DONATION_ITEM_FAIL';